# Session - 3 Data Processing part 1

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Task 1.
Download a small sample of IPL match data (CSV) with some missing values in player stats. Load it using pandas and print the number of missing values in each column.

In [3]:
df = pd.read_csv(r"C:\Users\DHRUV MODI\Documents\TOPS\Data set\ipl_player_data.csv")
df.isnull().sum()

player_name    0
player_age     3
team           2
venue          0
player_role    0
dtype: int64

# Task 2.
For the 'player_age' column in your IPL dataset, fill all missing values with the median age using pandas' fillna() method and display the updated column.

In [4]:
median_age = df['player_age'].median()
df['player_age'] = df['player_age'].fillna(median_age)
df.isnull().sum()

player_name    0
player_age     0
team           2
venue          0
player_role    0
dtype: int64

# Task 3.
Suppose the 'team' column in your IPL dataset contains missing values. Replace all missing team names with the constant value 'Unknown' and print the first 10 rows.

In [5]:
df['team'] = df['team'].fillna('Unknown')
df.head(10)

       player_name  player_age     team                   venue player_role
0      Virat Kohli        35.0      RCB  M. Chinnaswamy Stadium     Batsman
1         MS Dhoni        42.0      CSK  MA Chidambaram Stadium     Batsman
2     Rohit Sharma        36.0       MI        Wankhede Stadium     Batsman
3   Jasprit Bumrah        33.0       MI        Wankhede Stadium      Bowler
4         KL Rahul        31.0      LSG   Ekana Cricket Stadium     Batsman
5    Hardik Pandya        30.0       GT   Narendra Modi Stadium  Allrounder
6     Rishabh Pant        33.0       DC    Arun Jaitley Stadium     Batsman
7  Ravindra Jadeja        35.0      CSK  MA Chidambaram Stadium  Allrounder
8   Shikhar Dhawan        38.0     PBKS             PCA Stadium     Batsman
9     Shreyas Iyer        29.0  Unknown        Wankhede Stadium     Batsman

# Task 4.
Take the 'venue' column (categorical) from your IPL dataset and apply one-hot encoding using pandas' get_dummies(). Show the resulting DataFrame with the new columns.

In [6]:
df_encoded = pd.get_dummies(df, columns=['venue'], dtype=int)
df_encoded.head()

,player_name,player_age,team,player_role,venue_Arun Jaitley Stadium,venue_Ekana Cricket Stadium,venue_M. Chinnaswamy Stadium,venue_MA Chidambaram Stadium,venue_Narendra Modi Stadium,venue_PCA Stadium,venue_Rajiv Gandhi Stadium,venue_Sawai Mansingh Stadium,venue_Wankhede Stadium
0,Virat Kohli,35.0,RCB,Batsman,0,0,1,0,0,0,0,0,0
1,MS Dhoni,42.0,CSK,Batsman,0,0,0,1,0,0,0,0,0
2,Rohit Sharma,36.0,MI,Batsman,0,0,0,0,0,0,0,0,1
3,Jasprit Bumrah,33.0,MI,Bowler,0,0,0,0,0,0,0,0,1
4,KL Rahul,31.0,LSG,Batsman,0,1,0,0,0,0,0,0,0

# Task 5.
Use LabelEncoder from sklearn to encode the 'player_role' column (e.g., Batsman, Bowler, Allrounder) in your IPL dataset, and display the mapping from original roles to encoded values.<br><br><em><strong>Hint:</strong> Use LabelEncoder's classes_ attribute to see the mapping.</em>

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
encoder = LabelEncoder()

In [9]:
df['player_role_encoded'] = encoder.fit_transform(df['player_role'])

In [ ]:
encoder.classes_

array(['Allrounder', 'Batsman', 'Bowler'], dtype=object)

In [14]:
df[['player_role', 'player_role_encoded']].head()

  player_role  player_role_encoded
0     Batsman                    1
1     Batsman                    1
2     Batsman                    1
3      Bowler                    2
4     Batsman                    1